on:
  push:
    branches:
      - staging
name: ðŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ðŸ“‚ Sync filez
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.bystash.co
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: public_staging/
        exclude:
          - **/.git*
          - **/.github*
          - **/.git*/**
          # - fileToExclude.txt        
